### ISSUE TITLE
Suggestions for kb 5, rebase

### ISSUE THREAD

**Issue by knortema** [ryandeussing/kbsync#1]
Hey Ryan -- I have some suggestions to supplement the rebase topic in kb 5.

Sometimes GitLab requires us to manually rebase when there are merge conflicts that it can't resolve on its own. There are a couple of steps that we could add to address the procedure and include all the things that writers have to do. Here's the list of steps I have:

1. If you see the "Rebase manually" message in GitLab, open up a terminal window.
2. cd to your repo and type `git checkout main`
3. git pull
4. git switch into the branch with the conflict
5. git rebase origin/main. Any conflicts will show up as a response. Don't panic --- just examine each message carefully to find out which file(s) contain(s) the conflict(s). Just take them one at a time.
6. Open the first file in the list in your editor. The conflicts should be displayed within the file.
7. Click the version of the text you want to use. This resolves the conflict with the file.
8. Repeat this for any other conflicted files in the error message.
9. git add -A (or git add <filename>, if you have only one)
10. git rebase --continue
11. git push -f

If the rebase worked, the MR will change to show an "OK to merge" status in GitLab.

**Comment by ryandeussing** [comment]
I added a note to kb 5, but 'how to fix merge conflicts' seems out of scope for this guide
